# Generated by Django 4.2 on 2024-05-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imgPerfil'),
        ),
    ]
