# Generated by Django 4.2 on 2024-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='imgPerfil/img_default', upload_to='imgPerfil'),
        ),
    ]
