# Generated by Django 4.2 on 2024-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='imgPerfil/img_default.jpg', upload_to='imgPerfil'),
        ),
    ]
